name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
    
env:
  SOLUTION_FILE_PATH: .\build\bcm2836\buildbcm2836.sln

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
        BUILD_CONFIGURATION: [Release, Debug]
        PLATFORM: [ARM, ARM64]
    steps:
    - uses: actions/checkout@v2

    - name: Set up WDK version 2004 for bcmgenet backwards compatibility
      run: |
        $wdkSetupPath = "$Env:TEMP\wdksetup.exe"
        (New-Object Net.WebClient).DownloadFile('https://go.microsoft.com/fwlink/?linkid=2128854', $wdkSetupPath)
        Start-Process -FilePath $wdkSetupPath -ArgumentList "/quiet" -NoNewWindow -Wait

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{matrix.BUILD_CONFIGURATION}} /p:Platform=${{matrix.PLATFORM}} ${{env.SOLUTION_FILE_PATH}}
